server:
  port: 8088

spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**
        - id: writing
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**
        - id: point
          uri: http://localhost:8084
          predicates:
            - Path=/points/**
        - id: subscriber
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /subscriptions/**, /auth/**, /events/**
        - id: platform
          uri: http://localhost:8086
          predicates:
            - Path=/books/**
        - id: ai
          uri: http://localhost:8087
          predicates:
            - Path=/publishings/**, /ai/**

        # ✅ React 앱 정적 파일 서빙 라우팅 추가
        - id: frontend
          uri: forward:/index.html
          predicates:
            - Path=/

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**
        - id: writing
          uri: http://writing:8080
          predicates:
            - Path=/manuscripts/**
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**
        - id: subscriber
          uri: http://subscriber:8080
          predicates:
            - Path=/users/**, /subscriptions/**, /auth/**, /events/**
        - id: platform
          uri: http://platform:8080
          predicates:
            - Path=/books/**
        - id: ai
          uri: http://ai:8080
          predicates:
            - Path=/publishings/**, /ai/**

        # ✅ Docker 환경에서도 프론트 라우팅 추가
        - id: frontend
          uri: forward:/index.html
          predicates:
            - Path=/

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8080
