server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**
        - id: writing
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**
        - id: point
          uri: http://localhost:8084
          predicates:
            - Path=/points/**
        - id: subscriber
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /subscriptions/**, /auth/**, /events/**
        - id: platform
          uri: http://localhost:8086
          predicates:
            - Path=/books/**
        - id: ai
          uri: http://localhost:8087
          predicates:
            - Path=/publishings/**
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**
        - id: writing
          uri: http://writing:8080
          predicates:
            - Path=/manuscripts/**
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**
        - id: subscriber
          uri: http://subscriber:8080
          predicates:
            - Path=/users/**, /subscriptions/**, /auth/**, /events/**
        - id: platform
          uri: http://platform:8080
          predicates:
            - Path=/books/**
        - id: ai
          uri: http://ai:8080
          predicates:
            - Path=/publishings/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080