server:
  port: 8084
  error:
    include-message: always  # 예외 메시지를 HTTP 응답에 포함

spring:
  application:
    name: point

---

spring:
  profiles: default

  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 DB (또는 jdbc:h2:file:./data/pointdb 로 변경 가능)
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        jdbc:
          time_zone: Asia/Seoul

  sql:
    init:
      mode: always

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: point
          destination: millie
          contentType: application/json
        event-out:
          destination: millie
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

spring:
  profiles: docker

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: point
          destination: millie
          contentType: application/json
        event-out:
          destination: millie
          contentType: application/json
