server:
  port: 8084
  error:
    include-message: always 

spring:
  application:
    name: point

  datasource:
    url: jdbc:h2:file:./data/pointdb 
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        jdbc:
          time_zone: Asia/Seoul

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  cloud:
    stream:
      bindings:
        event-in:
          group: point
          destination: millie
          contentType: application/json
        event-out:
          destination: millie
          contentType: application/json
      kafka:
        binder:
          brokers: my-kafka:9092
logging:
  level:
    org.hibernate.type: trace
    org.springframework.kafka: debug
